// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6BobAUw5T3TCqT8ypcszbG
// Component: 1iwQpzF7nmRjw3G
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Navbar from "../../Navbar"; // plasmic-import: uTDo8cXNPa_B1XC/component
import Button from "../../Button"; // plasmic-import: KhbeBVaAisx47/component
import BlogPosts from "../../BlogPosts"; // plasmic-import: n3aIYan7r0SEV/component
import Footer from "../../Footer"; // plasmic-import: nmBaA0odzpiNWE/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent

import { useScreenVariants as useScreenVariantsuXvTXvy0VuZNuyJ } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: UXvTXvy0VuZNuyJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fountain_fm_css from "../fountain_fm/plasmic_fountain_fm.module.css"; // plasmic-import: q7mc6yKyK23FBh7x1aGwnG/projectcss
import projectcss from "./plasmic_copy_of_fountain_listen_to_earn.module.css"; // plasmic-import: 6BobAUw5T3TCqT8ypcszbG/projectcss
import sty from "./Plasmic_6PurchaseSuccess.module.css"; // plasmic-import: 1iwQpzF7nmRjw3G/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: a-uf39TcX85gUT/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: S2Divheo_3CFcy/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: cF5YAR91eQ2yTs/icon

export type Plasmic_6PurchaseSuccess__VariantMembers = {};

export type Plasmic_6PurchaseSuccess__VariantsArgs = {};
type VariantPropType = keyof Plasmic_6PurchaseSuccess__VariantsArgs;
export const Plasmic_6PurchaseSuccess__VariantProps =
  new Array<VariantPropType>();

export type Plasmic_6PurchaseSuccess__ArgsType = {};
type ArgPropType = keyof Plasmic_6PurchaseSuccess__ArgsType;
export const Plasmic_6PurchaseSuccess__ArgProps = new Array<ArgPropType>();

export type Plasmic_6PurchaseSuccess__OverridesType = {
  root?: p.Flex<"div">;
  navbar?: p.Flex<typeof Navbar>;
  foreground9?: p.Flex<"div">;
  foreground8?: p.Flex<"div">;
  foreground?: p.Flex<"div">;
  headerCopy?: p.Flex<"div">;
  foreground2?: p.Flex<"div">;
  h3?: p.Flex<"h3">;
  button?: p.Flex<typeof Button>;
  foreground3?: p.Flex<"div">;
  foreground4?: p.Flex<"div">;
  blogPosts?: p.Flex<typeof BlogPosts>;
  footer?: p.Flex<typeof Footer>;
  reveal?: p.Flex<typeof Reveal>;
};

export interface Default_6PurchaseSuccessProps {}

export const default_6PurchaseSuccess__Args: Partial<Plasmic_6PurchaseSuccess__ArgsType> =
  {};

function Plasmic_6PurchaseSuccess__RenderFunc(props: {
  variants: Plasmic_6PurchaseSuccess__VariantsArgs;
  args: Plasmic_6PurchaseSuccess__ArgsType;
  overrides: Plasmic_6PurchaseSuccess__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, default_6PurchaseSuccess__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsuXvTXvy0VuZNuyJ()
  });

  return (
    <React.Fragment>
      {}

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              plasmic_fountain_fm_css.plasmic_tokens,
              sty.root
            )}
          >
            <div className={classNames(projectcss.all, sty.freeBox__h7M7Q)}>
              <Navbar
                data-plasmic-name={"navbar"}
                data-plasmic-override={overrides.navbar}
                className={classNames("__wab_instance", sty.navbar)}
              />

              {(
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              ) ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bEibH)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground9"}
                    data-plasmic-override={overrides.foreground9}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground9)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__omhvK
                      )}
                    >
                      {"What you can do on Fountain"}
                    </div>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__afbSu)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__e653)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zaSiq)}
                        displayHeight={"60px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/copy_of_fountain_listen_to_earn/images/image43.png",
                          fullWidth: 200,
                          fullHeight: 200,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__p1Hpq
                        )}
                      >
                        <Icon8Icon
                          className={classNames(projectcss.all, sty.svg__izJhp)}
                          role={"img"}
                        />
                      </div>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__bM6O)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9Zgh7
                        )}
                      >
                        {"EARN"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0Bq6E
                        )}
                      >
                        {"Get paid to listen to podcasts"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__t8Ah)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__lO2Qo)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__yplXl)}
                        displayHeight={"60px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/copy_of_fountain_listen_to_earn/images/image44.png",
                          fullWidth: 200,
                          fullHeight: 200,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__s5Keq
                        )}
                      >
                        <Icon8Icon
                          className={classNames(projectcss.all, sty.svg__k0E6R)}
                          role={"img"}
                        />
                      </div>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__t2FAc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__educX
                        )}
                      >
                        {"SUPPORT"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__hCxDx
                        )}
                      >
                        {"Give back to podcasts you love"}
                      </div>
                    </p.Stack>
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__wb1IN)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__bNVb)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__glmSj)}
                        displayHeight={"60px" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"auto" as const}
                        loading={"lazy" as const}
                        src={{
                          src: "/plasmic/copy_of_fountain_listen_to_earn/images/image45.png",
                          fullWidth: 200,
                          fullHeight: 200,
                          aspectRatio: undefined
                        }}
                      />
                    </div>

                    {false ? (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tpWin
                        )}
                      >
                        <Icon8Icon
                          className={classNames(projectcss.all, sty.svg__mlStx)}
                          role={"img"}
                        />
                      </div>
                    ) : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__yA5Rg)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bJczQ
                        )}
                      >
                        {"SHARE"}
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tbu6Q
                        )}
                      >
                        {"Share podcasts with friends"}
                      </div>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              ) : null}
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___39GF)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground8"}
                    data-plasmic-override={overrides.foreground8}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground8)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lmnb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aNzyQ
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__hcYgF)}
                          displayHeight={"56px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"56px" as const}
                          src={
                            "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png" as const
                          }
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rIz0W
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__su3Ul
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__l5210
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4FJO
                          )}
                        >
                          {"EARN"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zFFvQ
                          )}
                        >
                          {"Get paid to listen to podcasts"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__e5WJ9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bsygt
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__aZhcT)}
                          displayHeight={"56px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"56px" as const}
                          src={
                            "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/banana_1f34c.png" as const
                          }
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hpy6P
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9IrEx
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___71Zip
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lgv7
                          )}
                        >
                          {"SUPPORT"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___203Ue
                          )}
                        >
                          {"Give back to podcasts you love"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0736X
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zWrZk
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__v2QHb)}
                          displayHeight={"56px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"none" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"56px" as const}
                          src={
                            "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/cherries_1f352.png" as const
                          }
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__sgXuV
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dasc1
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n9Lu4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__n5K3
                          )}
                        >
                          {"SHARE"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cGKp
                          )}
                        >
                          {"Share podcasts with others"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              ) : null}
              {true ? (
                <section
                  className={classNames(projectcss.all, sty.section__vuC)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"foreground"}
                    data-plasmic-override={overrides.foreground}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.foreground)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___8Soew
                      )}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__aGt5R
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i7Xs
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox___9FM0Y
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__jc1Kl
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___616X9
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__g8E3Y)}
                              displayHeight={"auto" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/copy_of_fountain_listen_to_earn/images/image25.jpeg",
                                fullWidth: 200,
                                fullHeight: 200,
                                aspectRatio: undefined
                              }}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__ywez
                              )}
                            >
                              {"Earn"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__juK9G
                              )}
                            >
                              {"Get paid to listen to podcasts"}
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fErDy
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__sbbD0
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__iYlC
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___8Z0T
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img__qrNsN)}
                              displayHeight={"223px" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? ("100%" as const)
                                  : ("100%" as const)
                              }
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? ("lazy" as const)
                                  : ("lazy" as const)
                              }
                              src={
                                hasVariant(
                                  globalVariants,
                                  "screen",
                                  "mobileOnly"
                                )
                                  ? {
                                      src: "/plasmic/copy_of_fountain_listen_to_earn/images/image26.jpeg",
                                      fullWidth: 200,
                                      fullHeight: 200,
                                      aspectRatio: undefined
                                    }
                                  : {
                                      src: "/plasmic/copy_of_fountain_listen_to_earn/images/image26.jpeg",
                                      fullWidth: 200,
                                      fullHeight: 200,
                                      aspectRatio: undefined
                                    }
                              }
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__wRyBw
                              )}
                            >
                              {"Support"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__s8LF2
                              )}
                            >
                              {"Give back to podcasts you love"}
                            </div>
                          </p.Stack>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__o0VM
                          )}
                        >
                          {false ? (
                            <div
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__onL0T
                              )}
                            >
                              <Icon8Icon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__yoUzR
                                )}
                                role={"img"}
                              />
                            </div>
                          ) : null}

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zt5K
                            )}
                          >
                            <p.PlasmicImg
                              alt={""}
                              className={classNames(sty.img___4EduO)}
                              displayHeight={"222px" as const}
                              displayMaxHeight={"none" as const}
                              displayMaxWidth={"100%" as const}
                              displayMinHeight={"0" as const}
                              displayMinWidth={"0" as const}
                              displayWidth={"auto" as const}
                              loading={"lazy" as const}
                              src={{
                                src: "/plasmic/copy_of_fountain_listen_to_earn/images/image27.jpeg",
                                fullWidth: 200,
                                fullHeight: 200,
                                aspectRatio: undefined
                              }}
                            />

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___2MI0
                              )}
                            >
                              {"Share"}
                            </div>

                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lsj0Z
                              )}
                            >
                              {"Share podcasts with others"}
                            </div>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </section>
              ) : null}

              <div
                data-plasmic-name={"headerCopy"}
                data-plasmic-override={overrides.headerCopy}
                className={classNames(projectcss.all, sty.headerCopy)}
              >
                {true ? (
                  <p.Stack
                    as={"section"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.section___8G31B)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground2"}
                      data-plasmic-override={overrides.foreground2}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground2)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pLjUh
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gHrH9
                          )}
                        >
                          {"Podcaster Wallet"}
                        </div>

                        <h3
                          data-plasmic-name={"h3"}
                          data-plasmic-override={overrides.h3}
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            projectcss.__wab_text,
                            sty.h3
                          )}
                        >
                          {"Earning Bitcoin made easy for every podcaster\n"}
                        </h3>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p259L
                          )}
                        >
                          {
                            "Getting your show on the Lightning Network and seeing all the data should be easy. However, no simple user-friendly solutions exist for podcasters today. That's why we're launching the Podcaster Wallet.\n\netc."
                          }
                        </div>

                        <Button
                          data-plasmic-name={"button"}
                          data-plasmic-override={overrides.button}
                          className={classNames("__wab_instance", sty.button)}
                          shape={"rounded" as const}
                          showEndIcon={true}
                        >
                          {"Get started"}
                        </Button>
                      </p.Stack>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yefoS
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hR7Sz
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__a6WFz
                            )}
                          >
                            {"Join the Lightning Network in the Fountain app"}
                          </h5>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__inyrG
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eSl8B
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__jDyXc
                            )}
                          >
                            {"See your show's earnings and supporters"}
                          </h5>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wQ17
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__zGtl
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__pgEmi
                            )}
                          >
                            {"Read and reply to messages from all apps"}
                          </h5>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pn7Dv
                            )}
                            role={"img"}
                          />
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ol9Jf
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__eZiVo
                            )}
                          >
                            {"Split your earnings with other users"}
                          </h5>

                          <Icon16Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__s4Ypk
                            )}
                            role={"img"}
                          />
                        </div>
                      </div>
                    </p.Stack>
                  </p.Stack>
                ) : null}

                <div className={classNames(projectcss.all, sty.freeBox__oGv73)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vbQ7)}
                  >
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : true
                    ) ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mFdsH
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"foreground3"}
                          data-plasmic-override={overrides.foreground3}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.foreground3
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2___56Cxr
                            )}
                          >
                            {"Success!"}
                          </h2>

                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__bb74G
                            )}
                          >
                            {
                              "Your promotion has been successfully purchased.\n\nIt is currently being reviewed by the Fountain team and will be live within 24 hours.\n\nThank you.\n"
                            }
                          </h5>
                        </p.Stack>
                      </p.Stack>
                    ) : null}
                    {(
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? true
                        : false
                    ) ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yd0Sx
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          data-plasmic-name={"foreground4"}
                          data-plasmic-override={overrides.foreground4}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.foreground4
                          )}
                        >
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__vnD57
                            )}
                          >
                            {"Success!"}
                          </h2>

                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__xTiq
                            )}
                          >
                            {
                              "Your promotion has been successfully purchased.\n\nIt is currently being reviewed by the Fountain team and will be live within 24 hours.\n\nThank you.\n"
                            }
                          </h5>
                        </p.Stack>
                      </p.Stack>
                    ) : null}
                  </p.Stack>
                </div>
              </div>
            </div>

            {true ? (
              <BlogPosts
                data-plasmic-name={"blogPosts"}
                data-plasmic-override={overrides.blogPosts}
                className={classNames("__wab_instance", sty.blogPosts)}
              />
            ) : null}

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />

            <Reveal
              data-plasmic-name={"reveal"}
              data-plasmic-override={overrides.reveal}
              className={classNames("__wab_instance", sty.reveal)}
              triggerOnce={true}
            >
              {true ? (
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__hxKff)}
                  displayHeight={"auto" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"auto" as const}
                  src={"https://placekitten.com/300/200" as const}
                />
              ) : null}
            </Reveal>
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navbar",
    "foreground9",
    "foreground8",
    "foreground",
    "headerCopy",
    "foreground2",
    "h3",
    "button",
    "foreground3",
    "foreground4",
    "blogPosts",
    "footer",
    "reveal"
  ],
  navbar: ["navbar"],
  foreground9: ["foreground9"],
  foreground8: ["foreground8"],
  foreground: ["foreground"],
  headerCopy: [
    "headerCopy",
    "foreground2",
    "h3",
    "button",
    "foreground3",
    "foreground4"
  ],
  foreground2: ["foreground2", "h3", "button"],
  h3: ["h3"],
  button: ["button"],
  foreground3: ["foreground3"],
  foreground4: ["foreground4"],
  blogPosts: ["blogPosts"],
  footer: ["footer"],
  reveal: ["reveal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navbar: typeof Navbar;
  foreground9: "div";
  foreground8: "div";
  foreground: "div";
  headerCopy: "div";
  foreground2: "div";
  h3: "h3";
  button: typeof Button;
  foreground3: "div";
  foreground4: "div";
  blogPosts: typeof BlogPosts;
  footer: typeof Footer;
  reveal: typeof Reveal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  Plasmic_6PurchaseSuccess__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: Plasmic_6PurchaseSuccess__VariantsArgs;
    args?: Plasmic_6PurchaseSuccess__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<Plasmic_6PurchaseSuccess__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<Plasmic_6PurchaseSuccess__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: Plasmic_6PurchaseSuccess__ArgProps,
      internalVariantPropNames: Plasmic_6PurchaseSuccess__VariantProps
    });

    return Plasmic_6PurchaseSuccess__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "Plasmic_6PurchaseSuccess";
  } else {
    func.displayName = `Plasmic_6PurchaseSuccess.${nodeName}`;
  }
  return func;
}

export const Plasmic_6PurchaseSuccess = Object.assign(
  // Top-level Plasmic_6PurchaseSuccess renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navbar: makeNodeComponent("navbar"),
    foreground9: makeNodeComponent("foreground9"),
    foreground8: makeNodeComponent("foreground8"),
    foreground: makeNodeComponent("foreground"),
    headerCopy: makeNodeComponent("headerCopy"),
    foreground2: makeNodeComponent("foreground2"),
    h3: makeNodeComponent("h3"),
    button: makeNodeComponent("button"),
    foreground3: makeNodeComponent("foreground3"),
    foreground4: makeNodeComponent("foreground4"),
    blogPosts: makeNodeComponent("blogPosts"),
    footer: makeNodeComponent("footer"),
    reveal: makeNodeComponent("reveal"),

    // Metadata about props expected for Plasmic_6PurchaseSuccess
    internalVariantProps: Plasmic_6PurchaseSuccess__VariantProps,
    internalArgProps: Plasmic_6PurchaseSuccess__ArgProps
  }
);

export default Plasmic_6PurchaseSuccess;
/* prettier-ignore-end */
