// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6BobAUw5T3TCqT8ypcszbG
// Component: stkhY95T4Hefc5-
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fountain_fm_css from "../fountain_fm/plasmic_fountain_fm.module.css"; // plasmic-import: q7mc6yKyK23FBh7x1aGwnG/projectcss
import projectcss from "./plasmic_copy_of_fountain_listen_to_earn.module.css"; // plasmic-import: 6BobAUw5T3TCqT8ypcszbG/projectcss
import sty from "./PlasmicReferralCode.module.css"; // plasmic-import: stkhY95T4Hefc5-/css

export type PlasmicReferralCode__VariantMembers = {};

export type PlasmicReferralCode__VariantsArgs = {};
type VariantPropType = keyof PlasmicReferralCode__VariantsArgs;
export const PlasmicReferralCode__VariantProps = new Array<VariantPropType>();

export type PlasmicReferralCode__ArgsType = {
  code?: React.ReactNode;
};

type ArgPropType = keyof PlasmicReferralCode__ArgsType;
export const PlasmicReferralCode__ArgProps = new Array<ArgPropType>("code");

export type PlasmicReferralCode__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultReferralCodeProps {
  code?: React.ReactNode;
  className?: string;
}

export const defaultReferralCode__Args: Partial<PlasmicReferralCode__ArgsType> =
  {};

function PlasmicReferralCode__RenderFunc(props: {
  variants: PlasmicReferralCode__VariantsArgs;
  args: PlasmicReferralCode__ArgsType;
  overrides: PlasmicReferralCode__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultReferralCode__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_fountain_fm_css.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "Referral link",
        value: args.code
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicReferralCode__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicReferralCode__VariantsArgs;
    args?: PlasmicReferralCode__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicReferralCode__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicReferralCode__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicReferralCode__ArgProps,
      internalVariantPropNames: PlasmicReferralCode__VariantProps
    });

    return PlasmicReferralCode__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicReferralCode";
  } else {
    func.displayName = `PlasmicReferralCode.${nodeName}`;
  }
  return func;
}

export const PlasmicReferralCode = Object.assign(
  // Top-level PlasmicReferralCode renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicReferralCode
    internalVariantProps: PlasmicReferralCode__VariantProps,
    internalArgProps: PlasmicReferralCode__ArgProps
  }
);

export default PlasmicReferralCode;
/* prettier-ignore-end */
