// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6BobAUw5T3TCqT8ypcszbG
// Component: Hhb0qgZrwIivUOF
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import BlogPosts from "../../BlogPosts"; // plasmic-import: n3aIYan7r0SEV/component
import Navbar from "../../Navbar"; // plasmic-import: uTDo8cXNPa_B1XC/component
import CantFindWhatYoureLookingFor from "../../CantFindWhatYoureLookingFor"; // plasmic-import: krEvZIR-QOuhWpu/component
import Footer from "../../Footer"; // plasmic-import: nmBaA0odzpiNWE/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal"; // plasmic-import: R6s1FdhksG/codeComponent

import { useScreenVariants as useScreenVariantsuXvTXvy0VuZNuyJ } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: UXvTXvy0VuZNuyJ/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_fountain_fm_css from "../fountain_fm/plasmic_fountain_fm.module.css"; // plasmic-import: q7mc6yKyK23FBh7x1aGwnG/projectcss
import projectcss from "./plasmic_copy_of_fountain_listen_to_earn.module.css"; // plasmic-import: 6BobAUw5T3TCqT8ypcszbG/projectcss
import sty from "./PlasmicFaqPromotePodcast.module.css"; // plasmic-import: Hhb0qgZrwIivUOF/css

import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: a-uf39TcX85gUT/icon

export type PlasmicFaqPromotePodcast__VariantMembers = {};

export type PlasmicFaqPromotePodcast__VariantsArgs = {};
type VariantPropType = keyof PlasmicFaqPromotePodcast__VariantsArgs;
export const PlasmicFaqPromotePodcast__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFaqPromotePodcast__ArgsType = {};
type ArgPropType = keyof PlasmicFaqPromotePodcast__ArgsType;
export const PlasmicFaqPromotePodcast__ArgProps = new Array<ArgPropType>();

export type PlasmicFaqPromotePodcast__OverridesType = {
  root?: p.Flex<"div">;
  foreground9?: p.Flex<"div">;
  foreground8?: p.Flex<"div">;
  section?: p.Flex<"section">;
  foreground?: p.Flex<"div">;
  blogPosts?: p.Flex<typeof BlogPosts>;
  navbar?: p.Flex<typeof Navbar>;
  h2?: p.Flex<"h2">;
  cantFindWhatYoureLookingFor?: p.Flex<typeof CantFindWhatYoureLookingFor>;
  footer?: p.Flex<typeof Footer>;
  reveal?: p.Flex<typeof Reveal>;
};

export interface DefaultFaqPromotePodcastProps {}

export const defaultFaqPromotePodcast__Args: Partial<PlasmicFaqPromotePodcast__ArgsType> =
  {};

function PlasmicFaqPromotePodcast__RenderFunc(props: {
  variants: PlasmicFaqPromotePodcast__VariantsArgs;
  args: PlasmicFaqPromotePodcast__ArgsType;
  overrides: PlasmicFaqPromotePodcast__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultFaqPromotePodcast__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsuXvTXvy0VuZNuyJ()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"FAQ Item"}</title>
        <meta key="og:title" property="og:title" content={"FAQ Item"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"root"}
            data-plasmic-override={overrides.root}
            data-plasmic-root={true}
            data-plasmic-for-node={forNode}
            hasGap={true}
            className={classNames(
              projectcss.all,
              projectcss.root_reset,
              projectcss.plasmic_default_styles,
              projectcss.plasmic_mixins,
              projectcss.plasmic_tokens,
              plasmic_fountain_fm_css.plasmic_tokens,
              sty.root
            )}
          >
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__xk1Zi)}>
                {(
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? true
                    : false
                ) ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__zWsbA)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground9"}
                      data-plasmic-override={overrides.foreground9}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground9)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qeR0
                        )}
                      >
                        {"What you can do on Fountain"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__pDuqW)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___3JHid
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___4I7ZU)}
                          displayHeight={"60px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/copy_of_fountain_listen_to_earn/images/image43.png",
                            fullWidth: 200,
                            fullHeight: 200,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__lRx8V
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__acaHj
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__shEu
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rl2I
                          )}
                        >
                          {"EARN"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0DbLy
                          )}
                        >
                          {"Get paid to listen to podcasts"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__tm8Du)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__gWv1C
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__eaw1O)}
                          displayHeight={"60px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/copy_of_fountain_listen_to_earn/images/image44.png",
                            fullWidth: 200,
                            fullHeight: 200,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__v5XgJ
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mEyCg
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__cmWpR
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___29UmT
                          )}
                        >
                          {"SUPPORT"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nl1Bw
                          )}
                        >
                          {"Give back to podcasts you love"}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___0Xls2
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yiIue
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__lanJw)}
                          displayHeight={"60px" as const}
                          displayMaxHeight={"none" as const}
                          displayMaxWidth={"100%" as const}
                          displayMinHeight={"0" as const}
                          displayMinWidth={"0" as const}
                          displayWidth={"auto" as const}
                          loading={"lazy" as const}
                          src={{
                            src: "/plasmic/copy_of_fountain_listen_to_earn/images/image45.png",
                            fullWidth: 200,
                            fullHeight: 200,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__oySu8
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__c1M02
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___1I0We
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hGEe
                          )}
                        >
                          {"SHARE"}
                        </div>

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cWHm
                          )}
                        >
                          {"Share podcasts with friends"}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                ) : null}
                {true ? (
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___9Vn5S)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground8"}
                      data-plasmic-override={overrides.foreground8}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground8)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__n6K4O
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__uA3Mn
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__vcF3E)}
                            displayHeight={"56px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"56px" as const}
                            src={
                              "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/red-apple_1f34e.png" as const
                            }
                          />
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__skKm
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__n3KnV
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__amANl
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__yq7YS
                            )}
                          >
                            {"EARN"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kt3Ge
                            )}
                          >
                            {"Get paid to listen to podcasts"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__eci1U
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__vjcxP
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img__mcd)}
                            displayHeight={"56px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"56px" as const}
                            src={
                              "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/banana_1f34c.png" as const
                            }
                          />
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__hdL3
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg__kGDfU
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fD72P
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bcG7M
                            )}
                          >
                            {"SUPPORT"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oq2So
                            )}
                          >
                            {"Give back to podcasts you love"}
                          </div>
                        </p.Stack>
                      </p.Stack>

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__xsHrV
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___28Ewc
                          )}
                        >
                          <p.PlasmicImg
                            alt={""}
                            className={classNames(sty.img___5HgW)}
                            displayHeight={"56px" as const}
                            displayMaxHeight={"none" as const}
                            displayMaxWidth={"none" as const}
                            displayMinHeight={"0" as const}
                            displayMinWidth={"0" as const}
                            displayWidth={"56px" as const}
                            src={
                              "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/144/twitter/281/cherries_1f352.png" as const
                            }
                          />
                        </div>

                        {false ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__osN3O
                            )}
                          >
                            <Icon8Icon
                              className={classNames(
                                projectcss.all,
                                sty.svg___1Haoy
                              )}
                              role={"img"}
                            />
                          </div>
                        ) : null}

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tip2V
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tubEw
                            )}
                          >
                            {"SHARE"}
                          </div>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___04Cro
                            )}
                          >
                            {"Share podcasts with others"}
                          </div>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                ) : null}
                {true ? (
                  <section
                    data-plasmic-name={"section"}
                    data-plasmic-override={overrides.section}
                    className={classNames(projectcss.all, sty.section)}
                  >
                    <p.Stack
                      as={"div"}
                      data-plasmic-name={"foreground"}
                      data-plasmic-override={overrides.foreground}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.foreground)}
                    >
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__jgqfq
                        )}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__d81F8
                          )}
                        >
                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wr1Sw
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox___1KC9N
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__lYc7
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__e8TJw
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__nr1Vi)}
                                displayHeight={"auto" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={"100%" as const}
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"auto" as const}
                                loading={"lazy" as const}
                                src={{
                                  src: "/plasmic/copy_of_fountain_listen_to_earn/images/image25.jpeg",
                                  fullWidth: 200,
                                  fullHeight: 200,
                                  aspectRatio: undefined
                                }}
                              />

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__kVr1V
                                )}
                              >
                                {"Earn"}
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__ilDjK
                                )}
                              >
                                {"Get paid to listen to podcasts"}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__wqlv8
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__cIwn
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__ahcf5
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__wPsO5
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__mo4YD)}
                                displayHeight={"223px" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? ("100%" as const)
                                    : ("100%" as const)
                                }
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"auto" as const}
                                loading={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? ("lazy" as const)
                                    : ("lazy" as const)
                                }
                                src={
                                  hasVariant(
                                    globalVariants,
                                    "screen",
                                    "mobileOnly"
                                  )
                                    ? {
                                        src: "/plasmic/copy_of_fountain_listen_to_earn/images/image26.jpeg",
                                        fullWidth: 200,
                                        fullHeight: 200,
                                        aspectRatio: undefined
                                      }
                                    : {
                                        src: "/plasmic/copy_of_fountain_listen_to_earn/images/image26.jpeg",
                                        fullWidth: 200,
                                        fullHeight: 200,
                                        aspectRatio: undefined
                                      }
                                }
                              />

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__iC77O
                                )}
                              >
                                {"Support"}
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__yklE
                                )}
                              >
                                {"Give back to podcasts you love"}
                              </div>
                            </p.Stack>
                          </p.Stack>

                          <p.Stack
                            as={"div"}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___7Pvqq
                            )}
                          >
                            {false ? (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__hBnvV
                                )}
                              >
                                <Icon8Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__p9UHa
                                  )}
                                  role={"img"}
                                />
                              </div>
                            ) : null}

                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__tBdf6
                              )}
                            >
                              <p.PlasmicImg
                                alt={""}
                                className={classNames(sty.img__y5Ob3)}
                                displayHeight={"222px" as const}
                                displayMaxHeight={"none" as const}
                                displayMaxWidth={"100%" as const}
                                displayMinHeight={"0" as const}
                                displayMinWidth={"0" as const}
                                displayWidth={"auto" as const}
                                loading={"lazy" as const}
                                src={{
                                  src: "/plasmic/copy_of_fountain_listen_to_earn/images/image27.jpeg",
                                  fullWidth: 200,
                                  fullHeight: 200,
                                  aspectRatio: undefined
                                }}
                              />

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__hOis1
                                )}
                              >
                                {"Share"}
                              </div>

                              <div
                                className={classNames(
                                  projectcss.all,
                                  projectcss.__wab_text,
                                  sty.text__jUkkh
                                )}
                              >
                                {"Share podcasts with others"}
                              </div>
                            </p.Stack>
                          </p.Stack>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </section>
                ) : null}
              </div>
            ) : null}
            {true ? (
              <BlogPosts
                data-plasmic-name={"blogPosts"}
                data-plasmic-override={overrides.blogPosts}
                className={classNames("__wab_instance", sty.blogPosts)}
              />
            ) : null}

            <Navbar
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames("__wab_instance", sty.navbar)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__cX4)}>
              {true ? (
                <div className={classNames(projectcss.all, sty.freeBox__p8BBy)}>
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__iabYj
                    )}
                    component={Link}
                    href={"/faqs" as const}
                    platform={"nextjs"}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eyEIe
                      )}
                    >
                      {"< FAQ"}
                    </div>
                  </p.PlasmicLink>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__nrQ3)}
                  >
                    <h2
                      data-plasmic-name={"h2"}
                      data-plasmic-override={overrides.h2}
                      className={classNames(
                        projectcss.all,
                        projectcss.h2,
                        projectcss.__wab_text,
                        sty.h2
                      )}
                    >
                      {"How do I promote my podcast on Fountain?"}
                    </h2>

                    <h6
                      className={classNames(
                        projectcss.all,
                        projectcss.h6,
                        projectcss.__wab_text,
                        sty.h6__rd5D6
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {
                            "If you have the Fountain Podcaster Wallet you can get your content in front of listeners on the Discover page by promoting an episode or clip. You can create new promotions from your show page in Fountain. \n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Promote your show"}
                        </span>
                        <React.Fragment>
                          {
                            "\nPromoting you show will automatically promote your latest episode on the Discover page until your campaign budget runs out. Select Promote Show and press continue to see a preview of how your promotion will look on the Discover page. Use the sliders to choose your promotion budget and the maximum amount (in sats) that users can earn by listening to the full episode. \n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Promote an episode"}
                        </span>
                        <React.Fragment>
                          {
                            "\nTo promote an episode, select Promote Episode and press continue to see a preview of how your promoted episode will look on the Discover page. Use the sliders to choose your promotion budget and the maximum amount (in sats) that users can earn by listening to the full episode.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Promote a clip"}
                        </span>
                        <React.Fragment>
                          {
                            "\nYou can promote clips of your show created by you or other Fountain users. To promote a clip, first you need to make sure that you have a clip to promote. Select Promote Clip and chose the clip you wish to promote, then press continue. Use the sliders to choose your promotion budget and the maximum amount (in sats) that users can earn by listening to the full clip.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Estimated reach"}
                        </span>
                        <React.Fragment>
                          {
                            "\nThe promotion budget and max earnings settings you choose will affect the amount the minimum number of listeners you can expect to reach with your promotion and the cost per listen. Minimum listener reach estimates do not take into account for listeners who don’t listen to the full episode. When this happens the budget that is not spent gets recycled back into your promotion budget, increasing your reach and reducing cost per listen.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Fountain’s fees"}
                        </span>
                        <React.Fragment>
                          {
                            "\nAll promotions are subject to a 20% fee, which is priced into the total cost. This means that 80% of your campaign budget gets paid directly to users who listen to your promotion. For example, if you set a budget of $50 then $40 will be your user earnings budget.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Paying for your promotion"}
                        </span>
                        <React.Fragment>
                          {
                            "\nPress purchase promotion when you’re ready and you will be able to pay with a credit card. When your payment has gone through, you will see the payment success screen and get take back to the Fountain home page.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Approving your promotion"}
                        </span>
                        <React.Fragment>
                          {
                            "\nAfter you have paid for your promotion, there is a 24-hour review period before your promotion is served to users. You can check the status of your promotions in the Promotions tab on your Show Page. When it has been approved, the status will change from Pending to Live.\n\n"
                          }
                        </React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ textDecorationLine: "underline" }}
                        >
                          {"Analytics for your promotion"}
                        </span>
                        <React.Fragment>
                          {
                            "\nTo see how your live promotions are performing, go to the Promotions tab on your Show page and click on a promotion to see your performance metrics.\n\n- User earnings budget: your total budget for the promotion after Fountain’s fee is applied\n- Budget spent: how much has been paid to users so far\n- Budget remaining: how much of your budget is remaining\n- Max earnings: Maximum user earnings when listening to your promotion in full\n- Impressions: how many times your promotion was seen on the Discover page\n- Listens: how many times your promotion was played\n- Average impression cost: how much you’re paying to get your ad seen on the Discover page\n- Average listen cost: how much you’re paying each user for listening\n\nWhen your budget has run out, the promotion will end and the status will change from Live to Complete. You can still see the data for your promotion in the Promotion tab after it ends."
                          }
                        </React.Fragment>
                      </React.Fragment>
                    </h6>

                    <div
                      className={classNames(projectcss.all, sty.freeBox__dMFgt)}
                    >
                      <h6
                        className={classNames(
                          projectcss.all,
                          projectcss.h6,
                          projectcss.__wab_text,
                          sty.h6__iDbtz
                        )}
                      >
                        <React.Fragment>
                          <React.Fragment>{""}</React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ color: "#000000", fontWeight: 700 }}
                          >
                            {"Next"}
                          </span>
                          <React.Fragment>{""}</React.Fragment>
                        </React.Fragment>
                      </h6>

                      <p.PlasmicLink
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__bt5De
                        )}
                        component={Link}
                        href={"/faqs/running-my-own-node" as const}
                        platform={"nextjs"}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__edAJw
                          )}
                        >
                          {
                            "Can I run my own node using the Fountain Podcaster Wallet?"
                          }
                        </div>
                      </p.PlasmicLink>
                    </div>
                  </div>
                </div>
              ) : null}
            </div>

            <CantFindWhatYoureLookingFor
              data-plasmic-name={"cantFindWhatYoureLookingFor"}
              data-plasmic-override={overrides.cantFindWhatYoureLookingFor}
              className={classNames(
                "__wab_instance",
                sty.cantFindWhatYoureLookingFor
              )}
            />

            <Footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames("__wab_instance", sty.footer)}
            />

            {true ? (
              <Reveal
                data-plasmic-name={"reveal"}
                data-plasmic-override={overrides.reveal}
                className={classNames("__wab_instance", sty.reveal)}
                triggerOnce={true}
              >
                {true ? (
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__mOp1Z)}
                    displayHeight={"auto" as const}
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"none" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"auto" as const}
                    src={"https://placekitten.com/300/200" as const}
                  />
                ) : null}
              </Reveal>
            ) : null}
          </p.Stack>
        ) : null}
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "foreground9",
    "foreground8",
    "section",
    "foreground",
    "blogPosts",
    "navbar",
    "h2",
    "cantFindWhatYoureLookingFor",
    "footer",
    "reveal"
  ],
  foreground9: ["foreground9"],
  foreground8: ["foreground8"],
  section: ["section", "foreground"],
  foreground: ["foreground"],
  blogPosts: ["blogPosts"],
  navbar: ["navbar"],
  h2: ["h2"],
  cantFindWhatYoureLookingFor: ["cantFindWhatYoureLookingFor"],
  footer: ["footer"],
  reveal: ["reveal"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  foreground9: "div";
  foreground8: "div";
  section: "section";
  foreground: "div";
  blogPosts: typeof BlogPosts;
  navbar: typeof Navbar;
  h2: "h2";
  cantFindWhatYoureLookingFor: typeof CantFindWhatYoureLookingFor;
  footer: typeof Footer;
  reveal: typeof Reveal;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFaqPromotePodcast__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFaqPromotePodcast__VariantsArgs;
    args?: PlasmicFaqPromotePodcast__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFaqPromotePodcast__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicFaqPromotePodcast__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicFaqPromotePodcast__ArgProps,
      internalVariantPropNames: PlasmicFaqPromotePodcast__VariantProps
    });

    return PlasmicFaqPromotePodcast__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFaqPromotePodcast";
  } else {
    func.displayName = `PlasmicFaqPromotePodcast.${nodeName}`;
  }
  return func;
}

export const PlasmicFaqPromotePodcast = Object.assign(
  // Top-level PlasmicFaqPromotePodcast renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    foreground9: makeNodeComponent("foreground9"),
    foreground8: makeNodeComponent("foreground8"),
    section: makeNodeComponent("section"),
    foreground: makeNodeComponent("foreground"),
    blogPosts: makeNodeComponent("blogPosts"),
    navbar: makeNodeComponent("navbar"),
    h2: makeNodeComponent("h2"),
    cantFindWhatYoureLookingFor: makeNodeComponent(
      "cantFindWhatYoureLookingFor"
    ),
    footer: makeNodeComponent("footer"),
    reveal: makeNodeComponent("reveal"),

    // Metadata about props expected for PlasmicFaqPromotePodcast
    internalVariantProps: PlasmicFaqPromotePodcast__VariantProps,
    internalArgProps: PlasmicFaqPromotePodcast__ArgProps
  }
);

export default PlasmicFaqPromotePodcast;
/* prettier-ignore-end */
